<a href="https://colab.research.google.com/github/sharvani1357/Deep-Learning/blob/main/deeplearning(Perceptron).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Perceptron (Binary Classification)
###Example:study hours -> pass(1)/Fail(0)

In [ ]:
import numpy as np

##Prepare Training Data

In [ ]:
#training Data
x=np.array([1,2,3,4]) #Study Hours
y=np.array([0,0,1,1]) # Fail(0)/Pass(1)
x,y

(array([1, 2, 3, 4]), array([0, 0, 1, 1]))

## Initialize Parameters

In [ ]:
w=0.0
b=0.0
learning_rate=1
epochs=5
print("Initial Weight:",w)
print("Initial Bias:",b)

Initial Weight: 0.0
Initial Bias: 0.0


## Define Activation Function(Step Function)

In [ ]:
def step_function(z):
  return 1 if z>=0 else 0

##Training Loop

In [ ]:
for epoch in range(epochs):
  print(f"\nEpoch {epoch+1}")
  for i in range(len(x)):
    #1.Compute weighted sum
    z=w * x[i] + b
    #2.Apply Activation function
    y_pred=step_function(z)
    #3.compute the erro
    error=y[i] - y_pred
    #4.update bias
    w=w+learning_rate*error*x[i]
    #5.update Bias
    b=b+learning_rate*error
    print(f"input:{x[i]},predicted:{y_pred},Actual:{y[i]},w:{w},b:{b}")



Epoch 1
input:1,predicted:1,Actual:0,w:-1.0,b:-1.0
input:2,predicted:0,Actual:0,w:-1.0,b:-1.0
input:3,predicted:0,Actual:1,w:2.0,b:0.0
input:4,predicted:1,Actual:1,w:2.0,b:0.0

Epoch 2
input:1,predicted:1,Actual:0,w:1.0,b:-1.0
input:2,predicted:1,Actual:0,w:-1.0,b:-2.0
input:3,predicted:0,Actual:1,w:2.0,b:-1.0
input:4,predicted:1,Actual:1,w:2.0,b:-1.0

Epoch 3
input:1,predicted:1,Actual:0,w:1.0,b:-2.0
input:2,predicted:1,Actual:0,w:-1.0,b:-3.0
input:3,predicted:0,Actual:1,w:2.0,b:-2.0
input:4,predicted:1,Actual:1,w:2.0,b:-2.0

Epoch 4
input:1,predicted:1,Actual:0,w:1.0,b:-3.0
input:2,predicted:0,Actual:0,w:1.0,b:-3.0
input:3,predicted:1,Actual:1,w:1.0,b:-3.0
input:4,predicted:1,Actual:1,w:1.0,b:-3.0

Epoch 5
input:1,predicted:0,Actual:0,w:1.0,b:-3.0
input:2,predicted:0,Actual:0,w:1.0,b:-3.0
input:3,predicted:1,Actual:1,w:1.0,b:-3.0
input:4,predicted:1,Actual:1,w:1.0,b:-3.0


In [ ]:
print("\n Final weight:",w)
print("final bias:",b)


 Final weight: 1.0
final bias: -3.0


##Testing the Model

In [ ]:
test_value=2.9
z=w*test_value+b
prediction=step_function(z)
print(f"for study hours {test_value},prediction:",prediction)

for study hours 2.9,prediction: 0


##Preceptron AND Gate

In [ ]:
import numpy as np
x=np.array([
    [0,0],[0,1],[1,0],[1,1]
])
y=np.array([0,0,0,1,1])
x,y


(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1, 1]))

In [ ]:
w=np.zeros(2)
b=0
learning_rate=0.1
epochs=10
print("initial weights:",w)
print("initial bias:",b)

initial weights: [0. 0.]
initial bias: 0


Train Perceptron

In [ ]:
for epoch in range(epochs):
  print(f"\nEpoch {epoch+1}")
  for i in range(len(x)):
    z=np.dot(w,x[i])+b
    y_pred=step_function(z)
    error=y[i]-y_pred
    w=w+learning_rate*error*x[i]
    b=b+learning_rate*error
    print(f"Input:{x[i]},Predicted:{y_pred},Actual:{y[i]},w:{w},b:{b}")



Epoch 1
Input:[0 0],Predicted:1,Actual:0,w:[0. 0.],b:-0.1
Input:[0 1],Predicted:0,Actual:0,w:[0. 0.],b:-0.1
Input:[1 0],Predicted:0,Actual:0,w:[0. 0.],b:-0.1
Input:[1 1],Predicted:0,Actual:1,w:[0.1 0.1],b:0.0

Epoch 2
Input:[0 0],Predicted:1,Actual:0,w:[0.1 0.1],b:-0.1
Input:[0 1],Predicted:1,Actual:0,w:[0.1 0. ],b:-0.2
Input:[1 0],Predicted:0,Actual:0,w:[0.1 0. ],b:-0.2
Input:[1 1],Predicted:0,Actual:1,w:[0.2 0.1],b:-0.1

Epoch 3
Input:[0 0],Predicted:0,Actual:0,w:[0.2 0.1],b:-0.1
Input:[0 1],Predicted:1,Actual:0,w:[0.2 0. ],b:-0.2
Input:[1 0],Predicted:1,Actual:0,w:[0.1 0. ],b:-0.30000000000000004
Input:[1 1],Predicted:0,Actual:1,w:[0.2 0.1],b:-0.20000000000000004

Epoch 4
Input:[0 0],Predicted:0,Actual:0,w:[0.2 0.1],b:-0.20000000000000004
Input:[0 1],Predicted:0,Actual:0,w:[0.2 0.1],b:-0.20000000000000004
Input:[1 0],Predicted:0,Actual:0,w:[0.2 0.1],b:-0.20000000000000004
Input:[1 1],Predicted:1,Actual:1,w:[0.2 0.1],b:-0.20000000000000004

Epoch 5
Input:[0 0],Predicted:0,Actual:0,w

In [ ]:
print("\n Final Weights:",w)
print("Final Bias:",b)


 Final Weights: [0.2 0.1]
Final Bias: -0.20000000000000004


##Test Model

In [ ]:
print("\n Testing AND Gate")
for i in range(len(x)):
  z=np.dot(w,x[i])+b
  prediction=step_function(z)
  print("Input:",x[i],"Prediction:",prediction)


 Testing AND Gate
Input: [0 0] Prediction: 0
Input: [0 1] Prediction: 0
Input: [1 0] Prediction: 0
Input: [1 1] Prediction: 1


##Perceptron for OR Gate


In [ ]:
import numpy as np

# Input dataset
x = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

# OR gate outputs
y = np.array([0,1,1,1])

# Step function
def step_function(z):
    if z >= 0:
        return 1
    else:
        return 0

# Initialize weights and bias
w = np.zeros(2)
b = 0
learning_rate = 0.1
epochs = 10

print("Initial weights:", w)
print("Initial bias:", b)

# Training
for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    for i in range(len(x)):
        z = np.dot(w, x[i]) + b
        y_pred = step_function(z)
        error = y[i] - y_pred

        w = w + learning_rate * error * x[i]
        b = b + learning_rate * error

        print(f"Input:{x[i]}, Predicted:{y_pred}, Actual:{y[i]}, w:{w}, b:{b}")

print("\nFinal Weights:", w)
print("Final Bias:", b)

# Testing
print("\nTesting OR Gate")
for i in range(len(x)):
    z = np.dot(w, x[i]) + b
    prediction = step_function(z)
    print("Input:", x[i], "Prediction:", prediction)

Initial weights: [0. 0.]
Initial bias: 0

Epoch 1
Input:[0 0], Predicted:1, Actual:0, w:[0. 0.], b:-0.1
Input:[0 1], Predicted:0, Actual:1, w:[0.  0.1], b:0.0
Input:[1 0], Predicted:1, Actual:1, w:[0.  0.1], b:0.0
Input:[1 1], Predicted:1, Actual:1, w:[0.  0.1], b:0.0

Epoch 2
Input:[0 0], Predicted:1, Actual:0, w:[0.  0.1], b:-0.1
Input:[0 1], Predicted:1, Actual:1, w:[0.  0.1], b:-0.1
Input:[1 0], Predicted:0, Actual:1, w:[0.1 0.1], b:0.0
Input:[1 1], Predicted:1, Actual:1, w:[0.1 0.1], b:0.0

Epoch 3
Input:[0 0], Predicted:1, Actual:0, w:[0.1 0.1], b:-0.1
Input:[0 1], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1
Input:[1 0], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1
Input:[1 1], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1

Epoch 4
Input:[0 0], Predicted:0, Actual:0, w:[0.1 0.1], b:-0.1
Input:[0 1], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1
Input:[1 0], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1
Input:[1 1], Predicted:1, Actual:1, w:[0.1 0.1], b:-0.1

Epoch 5
Input:[0 0], Predicted:0,

##XOR gate

In [ ]:
import numpy as np

# Input dataset
x = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

# XOR outputs
y = np.array([0,1,1,0])

# Step function
def step_function(z):
    if z >= 0:
        return 1
    else:
        return 0

# Initialize weights and bias
w = np.zeros(2)
b = 0
learning_rate = 0.1
epochs = 10

print("Initial weights:", w)
print("Initial bias:", b)

# Training
for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    for i in range(len(x)):
        z = np.dot(w, x[i]) + b
        y_pred = step_function(z)
        error = y[i] - y_pred

        w = w + learning_rate * error * x[i]
        b = b + learning_rate * error

        print(f"Input:{x[i]}, Predicted:{y_pred}, Actual:{y[i]}, w:{w}, b:{b}")

print("\nFinal Weights:", w)
print("Final Bias:", b)

# Testing
print("\nTesting XOR Gate")
for i in range(len(x)):
    z = np.dot(w, x[i]) + b
    prediction = step_function(z)
    print("Input:", x[i], "Prediction:", prediction)

Initial weights: [0. 0.]
Initial bias: 0

Epoch 1
Input:[0 0], Predicted:1, Actual:0, w:[0. 0.], b:-0.1
Input:[0 1], Predicted:0, Actual:1, w:[0.  0.1], b:0.0
Input:[1 0], Predicted:1, Actual:1, w:[0.  0.1], b:0.0
Input:[1 1], Predicted:1, Actual:0, w:[-0.1  0. ], b:-0.1

Epoch 2
Input:[0 0], Predicted:0, Actual:0, w:[-0.1  0. ], b:-0.1
Input:[0 1], Predicted:0, Actual:1, w:[-0.1  0.1], b:0.0
Input:[1 0], Predicted:0, Actual:1, w:[0.  0.1], b:0.1
Input:[1 1], Predicted:1, Actual:0, w:[-0.1  0. ], b:0.0

Epoch 3
Input:[0 0], Predicted:1, Actual:0, w:[-0.1  0. ], b:-0.1
Input:[0 1], Predicted:0, Actual:1, w:[-0.1  0.1], b:0.0
Input:[1 0], Predicted:0, Actual:1, w:[0.  0.1], b:0.1
Input:[1 1], Predicted:1, Actual:0, w:[-0.1  0. ], b:0.0

Epoch 4
Input:[0 0], Predicted:1, Actual:0, w:[-0.1  0. ], b:-0.1
Input:[0 1], Predicted:0, Actual:1, w:[-0.1  0.1], b:0.0
Input:[1 0], Predicted:0, Actual:1, w:[0.  0.1], b:0.1
Input:[1 1], Predicted:1, Actual:0, w:[-0.1  0. ], b:0.0

Epoch 5
Input:[0 0]